---

#computername: Macbook-Air-de-Rene
#hostname: Macbook-Air-de-Rene.local

#finder_proxy_icon_hover_delay: 0

#safari_show_full_url_in_address_bar: true
#safari_open_safe_files_automatically: true
#safari_show_status_bar: true
#safari_show_developer_menu: true

#system_save_application_state_on_quit: no
#system_expand_save_panel_by_default: yes
#system_expand_print_panel_by_default: yes
#system_show_file_extensions_warning: no
#system_warn_before_emptying_the_trash: yes
#system_use_f_keys_as_standard_function_keys: yes
#system_index_network_storage_with_spotlight: no
#trackpad_tap_to_click: yes

#screensaver_ask_for_password: no
#screensaver_ask_for_password_in_seconds: 5

#shell_path: /usr/local/bin/zsh

homebrew_taps: []

homebrew_apps:
  - docker
  - iterm2
  - slack
  - spotify
  - tiles
  - whatsapp
  - zoom
  - vlc

homebrew_packages:
  - ansible
  - awscli
  - azure-cli
  - git
  - gotop
  - grep
  - helm
  - ipcalc
  - istioctl
  - jq
  - kind
  - kubernetes-cli
  - kubevela
  - k9s
  - mas
  - mtr
  - neofetch
  - nmap
  - openssh
  - stern
  - terraform
  - tree
  - vim
  - wget
  - watch
  - zsh

mas_apps:
  - { name: Amphetamine, id: 937984704 }
  - { name: Bitwarden, id: 1352778147 }
  - { name: Microsoft Remote Desktop, id: 1295203466 }
