---

- name: Everything's gonna be alright.
  hosts: localhost

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_env.USER }}.yml"
        - "defaults.yml"
      tags: [always]

  roles:
    - name: essentials
      tags: [essentials]

    - name: shell
      tags: [shell]

    - name: yadm
      tags: [yadm]

    - name: dev
      tags: [dev]

    - name: macos-settings
      tags: [settings]

    - name: settings/hostname
      tags: [hostname]

    - name: settings/safari
      tags: [settings-safari]

    - name: settings/system
      tags: [settings-system]

    - name: apps
      tags: [apps]
