---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
            - default.config.yml
          skip: true
      tags: ['always']
    - name: Verify Ansible meets the version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.14', '>=')"
        msg: >
          "This playbook requires at least Ansible 2.14"

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: mas
      tags: [mas]
    - role: settings
      tags: [settings]
