---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/cask
    - caskroom/drivers
    - caskroom/fonts
    - buo/cask-upgrade

- name: Install FFmpeg
  homebrew:
    name: ffmpeg
    state: latest
    install_options: with-chromaprint,with-fdk-aac,with-fontconfig,with-freetype,with-libvorbis,with-openh264,with-openssl,with-opus,with-rtmpdump,with-theora,with-tools,with-two-lame,with-wavpack,with-x265

- name: Install homebrew apps.
  homebrew:
    name: "{{ item }}"
  with_items:
    - youtube-dl

- name: Install casks.
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - alfred
    - bartender
    - cleanmymac
    - encryptme
    - dash
    - fantastical
    - firefox
    - font-fira-code
    - font-roboto
    - font-roboto-condensed
    - font-roboto-mono
    - gitup
    - google-chrome
    - gpg-suite
    - iterm2
    - java
    - kaleidoscope
    - mailmate
    - paw
    - plug
    - phpstorm
    - sequel-pro
    - slack
    - sonos
    - spotify
    - sublime-text
    - telegram-desktop
    - textual
    - transmit
    - tower
    - vlc
    - whatsapp

- include_role:
    name: mas
  tags: [mas]
  vars:
    mas_apps:
      - { name: 1Blocker, id: 1107421413 }
      - { name: 1Password, id: 443987910 }
      - { name: Amphetamine, id: 937984704 }
      - { name: Bear, id: 1091189122 }
      - { name: Day One, id: 1055511498 }
      - { name: Keynote, id: 409183694 }
      - { name: Neptunes, id: 1006739057 }
      - { name: Numbers, id: 409203825 }
      - { name: Outbank, id: 1094255754 }
      - { name: Pages, id: 409201541 }
      - { name: Patterns, id: 429449079 }
      - { name: Pixelmator, id: 407963104 }
      - { name: Reeder, id: 880001334 }
      - { name: Things, id: 904280696 }
      - { name: Tweetbot, id: 557168941 }
    mas_upgrade_all_apps: yes

- include_role:
    name: dock
  tags: [dock]
  vars:
    dock_remove_undefined: yes
    dock_apps:
      - name: MailMate
        path: /Applications/MailMate.app
      - name: Fantastical 2
        path: /Applications/Fantastical 2.app
      - name: Slack
        path: /Applications/Slack.app
      - name: Nachrichten
        path: /Applications/Messages.app
      - name: Safari
        path: /Applications/Safari.app
      - name: Google Chrome
        path: /Applications/Google Chrome.app
      - name: Sublime Text
        path: /Applications/Sublime Text.app
      - name: Spotify
        path: /Applications/Spotify.app
      - name: iTerm
        path: /Applications/iTerm.app
