---

- name: Tap PHP in Homebrew.
  homebrew_tap:
    name: homebrew/php

- name: Install PHP (this might take a while).
  homebrew:
    name: "{{ homebrew_php_basename }}"
    state: latest
    install_options: with-homebrew-curl,with-homebrew-libxml2,with-homebrew-libxslt,with-phpdbg

- name: Install PHP extensions.
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_php_extensions }}"

- name: Install composer.
  homebrew:
    name: composer
    state: latest

- name: Get globally installed packages
  shell: composer global info
  register: composer_global_info
  changed_when: false
  check_mode: no

- name: Install global composer packages.
  shell: composer global require {{ item }}
  with_items: "{{ composer_global_packages }}"
  when: item not in composer_global_info.stdout
